---
# yamllint disable rule:line-length
default_language_version:
  python: python3
repos:
  - repo: git://github.com/jameswoolfenden/pre-commit
    rev: v0.1.33
    hooks:
      - id: terraform-fmt
      - id: checkov-scan
        language_version: python3.7